### ISSUE TITLE
Does not resize view

### ISSUE THREAD

**Issue by batgun** [jhays/JHAdSupportedTemplate#1]
First of all its great piece of code but it has one issue. It does not resize previously created view.It just overlay existing items(like labels,buttons etc...)
So its not practical for existing apps

**Comment by jhays** [comment]
Thanks for the feedback. 

In a development version of JHAdSupportedTemplate I have been working on, I have added a method called "adjustViewForBannerView()" to the AdSupportedViewController. This method gets called when an ad banner is loaded- in subclasses of AdSupportedViewController, you can override this method and adjust your views based on the ad's position/frame. I will work on updating this repo with that code soon.

If you have any other ideas on an approach to resolve this issue, I'm open to any suggestions. 

Thanks!

**Comment by batgun** [comment]
I think, it'd be complete solution(possibly best in web) with that implementation. I will keep on eye for that update. Hope you will add soon since I am stuck on that for about a week.
Kind Regards

**Comment by jhays** [comment]
An update was just pushed with these changes! Hope it works for you.

**Comment by batgun** [comment]
Thanks for great help. But could not see any change currently.

**Comment by jhays** [comment]
My mistake! Looks like I committed the changes on a private bitbucket repo instead of this public github. I've just pushed the changes up to github so they should be available now.

**Comment by batgun** [comment]
I saw your adjustViewForBannerView method is empty and actually that point is the real problematic case in my case. It'd be better to use it in your example project

**Comment by jhays** [comment]
Yes- that function is empty- it is intended to be overridden by your subclasses of AdSupportedViewController. The method gets called when ad banners are displayed, and you have to write the necessary code to modify your views' frames or constraints to adjust for the ad banner view. 

I understand that a simpler drop-in solution would do the resizing for you, but at the moment I don't have a solution that will automatically resize custom content. Perhaps a future solution could check all constraints and if constraints are found pinned to the bottom or top layout guides (based on banner position), automatically adjust them to account for the adBannerBuffer. 

But for now, the solution to this problem is to override adjustViewForBannerView() in your subclasses of AdSupportedViewController, and handle the resizing yourself.

**Comment by batgun** [comment]
It was my main problem, anyways thanks for your patience and kind answers
